
export enum HttpStatusCode {
    OK = 200,
    CREATED = 201,
    ACCEPTED = 202,
    AMBIGUOUS = 300,
    MOVED_PERMANENTLY = 301,
    BAD_REQUEST = 400,
    UNAUTHORIZED = 401,
    FORBIDDEN = 403,
    NOT_FOUND = 404,
    CONFLICT = 409,
    INTERNAL_SERVER_ERROR = 500,
    NOT_IMPLEMENTED = 501,
    BAD_GATEWAY = 502,
}


export enum HttpStatusMessage {
    OK = "OK",
    CREATED = "CREATED",
    ACCEPTED = "ACCEPTED",
    NO_CONTENT = "NO_CONTENT",
    AMBIGUOUS = "AMBIGUOUS",
    MOVED_PERMANENTLY = "MOVED_PERMANENTLY",
    FOUND = "FOUND",
    BAD_REQUEST = "BAD_REQUEST",
    UNAUTHORIZED = "UNAUTHORIZED",
    FORBIDDEN = "FORBIDDEN",
    NOT_FOUND = "NOT_FOUND",
    CONFLICT = "CONFLICT",
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
    NOT_IMPLEMENTED = "NOT_IMPLEMENTED",
    BAD_GATEWAY = "BAD_GATEWAY",
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE",
}


export enum ExceptionMessage {
    NOT_FOUND = "NOT_FOUND",
    SOMETHING_WENT_WRONG = "SOMETHING_WENT_WRONG",
    ERROR_IN_DATA_SCRABE = "ERROR_IN_DATA_SCRABE",
    INVALID_DOMAIN_NAME = "INVALID_DOMAIN_NAME",
    FAIL_TO_FETCH_DATA = "FAIL_TO_FETCH_DATA",
    NO_DATA_FOUND_WITH_PROVIDED_SELECTOR = "NO_DATA_FOUND_WITH_PROVIDED_SELECTOR"
}


export enum SuccessMessage {
    DATA_SCRABE_SUCCESSFULLY = "DATA_SCRABE_SUCCESSFULLY"
}


export enum MSG {
    SUCCESS = "SUCCESS",
    ERROR = "ERROR",
}